version: '3.8'
 
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: events_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
 
  springboot:
    image: oussemajebali/eventsproject:latest
    container_name: springboot_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/events_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user_password
    ports:
      - "8080:8080"
    depends_on:
      - mysql
 
volumes:
  mysql_data: